---
version: "2"
plugins:
  duplication:
    enabled: false
  nodesecurity:
    enabled: true
exclude_patterns:
  - "node_modules/"
  - "migrations/"
  - "test/"
  - "scripts/"
  - "coverage/"
  - "migrate.js"
