version: '3'

volumes:
  db-data:
  yarn:
  nm-app:
  nm-admin:
  pw-deps:

services:
  app:
    build:
      dockerfile: Dockerfile-app
      context: .
    command: ["yarn", "watch"]
    volumes:
      - yarn:/usr/local/share/.cache/yarn
      - .:/app
      - /app/admin-client/
      - nm-app:/app/node_modules
    ports:
      - "1337:1337" # for the app itself
      - "8888:8888" # for viewing webpack-bundle-analyzer
      - "8080:8080" # for serving test coverage html
    depends_on:
      - db
      - redis
      - localstack
    environment:
      APP_HOSTNAME: http://localhost:1337
      DOMAIN: localhost:1337
      FEATURE_BUILD_TASKS: 'active'
      PORT: 1337
      PRODUCT: pages
      UAA_HOST: http://localhost:9000
      UAA_HOST_DOCKER_URL: http://uaa:8080
      USER_AUDITOR: federalist
      CLOUD_FOUNDRY_API_HOST: http://cf-mock:1234
      CLOUD_FOUNDRY_OAUTH_TOKEN_URL: http://cf-mock:1234/oauth/token
      CF_API_USERNAME: deploy_user
      CF_API_PASSWORD: deploy_pass
      PROXY_DOMAIN: localhost:1337
      AWS_ENDPOINT_URL: http://localstack:4566
      NODE_ENV: development
  bull-board:
    build:
      dockerfile: Dockerfile-app
      context: .
    command: ["scripts/wait-for-it.sh", "redis:6379", "--", "yarn", "start-bull-board:local"]
    volumes:
      - yarn:/usr/local/share/.cache/yarn
      - .:/app
      - /app/admin-client/
      - nm-app:/app/node_modules
    ports:
      - "1340:1340"
    depends_on:
      - redis
    environment:
      ADMIN_GITHUB_ORGANIZATION: FederalistLocal
      ADMIN_GITHUB_TEAM: federalist-local-admins
      APP_ENV: local
      APP_HOSTNAME: http://localhost:1340
      PORT: 1340
      PRODUCT: pages
      REDIS_URL: redis://redis:6379
      SESSION_SECRET: bull-board
      UAA_CLIENT_ID: pages-client
      UAA_CLIENT_SECRET: client-secret
      UAA_HOST_DOCKER_URL: http://uaa:8080
      UAA_LOGIN_HOST: http://localhost:9000
  admin-client:
    build:
      dockerfile: ./admin-client/Dockerfile-admin
      context: .
    volumes:
      - yarn:/usr/local/share/.cache/yarn
      - ./admin-client:/app
      - nm-admin:/app/node_modules
    ports:
      - "3000:3000"
      - "35729:35729"
    depends_on:
      - app
    command: ["yarn", "dev"]
    environment:
      API_URL: http://localhost:1337
  db:
    build:
      dockerfile: Dockerfile-db
      context: .
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # expose db on host at port 5433
    environment:
      POSTGRES_DB: federalist
      POSTGRES_TEST_DB: federalist-test
      POSTGRES_PASSWORD: password
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --loglevel warning
  echo:
    image: node:20.9-bullseye
    volumes:
      - yarn:/usr/local/share/.cache/yarn
      - .:/app
      - /app/admin-client/
      - nm-app:/app/node_modules
    environment:
      HOST: 0.0.0.0
      PORT: 8989
    command: node app/scripts/echo.js
  localstack:
    build:
      dockerfile: Dockerfile-localstack
      context: .
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
  localstack-setup:
    build:
      dockerfile: Dockerfile-app
      context: .
    volumes:
      - yarn:/usr/local/share/.cache/yarn
      - .:/app
      - nm-app:/app/node_modules
    command: ["scripts/wait-for-it.sh", "localstack:4566", "--", "yarn", "localstack-setup"]
    depends_on:
      - localstack
      - db # race condition waiting to happen as we don't wait for DB
    environment:
      NODE_ENV: development
      AWS_ENDPOINT_URL: http://localstack:4566
  cf-mock:
    build:
      dockerfile: Dockerfile-app
      context: .
    volumes:
      - yarn:/usr/local/share/.cache/yarn
      - .:/app
      - nm-app:/app/node_modules
    command: ["scripts/wait-for-it.sh", "db:5432", "--", "yarn", "cf-mock"]
    ports:
      - "1234:1234"
    depends_on:
      - db
      - localstack
    environment:
      NODE_ENV: development
      AWS_ENDPOINT_URL: http://localstack:4566