product: federalist
name: federalistapp
domain: federalistapp.18f.gov
memory: 256MB
instances: 2
env: production
env_postfix: ''
log_level: info
feature_auth_github: 'true'
feature_auth_uaa: 'false'
feature_bull_site_build_queue: 'false'
uaa_host: https://uaa.fr.cloud.gov
new_relic_app_name: web
proxy_domain: app.cloud.gov
cf_cdn_space_name: sites
