product: federalist
name: federalistapp-staging
domain: federalistapp-staging.18f.gov
app_subdomain: ''
memory: 128MB
instances: 2
env: staging
env_postfix: -staging
log_level: verbose
feature_auth_github: 'true'
feature_auth_uaa: 'false'
feature_bull_site_build_queue: 'true'
uaa_host: https://uaa.fr-stage.cloud.gov
new_relic_app_name: web-staging
proxy_domain: app.cloud.gov
cf_cdn_space_name: sites-staging
