############################
#  SHARED

env-cf: &env-cf
  CF_API: https://api.fr.cloud.gov
  CF_USERNAME: ((((deploy-env))-cf-username))
  CF_PASSWORD: ((((deploy-env))-cf-password))
  CF_ORG: gsa-18f-federalist
  CF_SPACE: ((deploy-env))
  CF_STACK: cflinuxfs4

test-admin-client: &test-admin-client
  - get: node
  - task: install-deps-admin-client
    file: src/ci/partials/install-deps-admin-client.yml
    image: node

  - task: lint-admin-client
    file: src/ci/partials/lint-admin-client.yml
    image: node

  - task: build-admin-client
    file: src/ci/partials/build-admin-client.yml
    image: node
    params:
      API_URL: https://((((deploy-env))-pages-domain))
      NODE_ENV: development

############################
#  JOBS

jobs:

  - name: test-and-deploy-api-pages
    plan:
      - get: src
        resource: pr-((deploy-env))
        params: {integration_tool: checkout}
        passed: [set-pipeline]
        trigger: true
      - put: gh-status
        inputs: [src]
        params: {state: pending}
      - in_parallel:
        - get: cf-image
        - get: redis
          params: {save: true}
        - get: postgres
          params: {save: true}
        - get: node
          params: {save: true}
      - task: install-deps-api
        file: src/ci/partials/install-deps-api.yml
        image: node

      - in_parallel:
        - task: lint-api
          file: src/ci/partials/lint-api.yml
          image: node

        - task: test-api
          privileged: true
          file: src/ci/partials/test-api.yml
        - do:
          - task: build-api
            file: src/ci/partials/build-api.yml
            image: node
            params:
              APP_HOSTNAME: https://((((deploy-env))-pages-domain))
              NODE_ENV: development
              PROXY_DOMAIN: sites.((((deploy-env))-pages-domain))
              FEATURE_BUILD_TASKS: true

          - task: deploy-api
            file: src/ci/partials/deploy.yml
            image: cf-image
            params:
              <<: *env-cf
              CF_APP_NAME: pages-((deploy-env))
              CF_MANIFEST: src/.cloudgov/manifest.yml
              CF_VARS_FILE: src/.cloudgov/vars/pages-((deploy-env)).yml
              CF_PATH: src
            on_failure:
              try:
                task: cancel-api-deployment
                file: src/ci/partials/cancel-deployment.yml
                image: cf-image
                params:
                  <<: *env-cf
                  CF_APP_NAME: pages-((deploy-env))

          - task: run-database-migrations
            file: src/ci/partials/run-task.yml
            image: cf-image
            params:
              <<: *env-cf
              APP_ENV: ((deploy-env))
              CF_APP_NAME: pages-((deploy-env))
              CF_TASK_NAME: run-migrations
              CF_TASK_COMMAND: 'yarn run migrate:up'
            on_failure:
              in_parallel:
                - put: gh-status
                  inputs: [src]
                  params: {state: failure}
                - put: slack
                  params:
                    text: |
                      :x: FAILED: to migrate database for pages ((deploy-env))
                      <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME?vars.deploy-env="((deploy-env))"|View build details>
                    channel: ((slack-channel))
                    username: ((slack-username))
                    icon_url: ((slack-icon-url))

    on_failure:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: failure}
        - put: slack
          params:
            text: |
              :x: FAILED: api deployment on pages ((deploy-env))
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME?vars.deploy-env="((deploy-env))"|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))
    on_success:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: success}
        - put: slack
          params:
            text: |
              :white_check_mark: SUCCESS: Successfully deployed api on pages ((deploy-env))
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME?vars.deploy-env="((deploy-env))"|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

  - name: test-and-deploy-admin-client-pages
    plan:
      - get: src
        resource: pr-((deploy-env))
        params: {integration_tool: checkout}
        passed: [set-pipeline]
        trigger: true
      - put: gh-status
        inputs: [src]
        params: {state: pending}

      - do: *test-admin-client
      - get: cf-image
      - task: configure-nginx
        file: src/ci/partials/configure-nginx.yml
        image: cf-image
        params:
          API_DOMAIN: ((((deploy-env))-pages-domain))

      - task: deploy-admin-client
        file: src/ci/partials/deploy.yml
        image: cf-image
        params:
          <<: *env-cf
          CF_APP_NAME: pages-admin-((deploy-env))
          CF_MANIFEST: src/.cloudgov/manifest.yml
          CF_VARS_FILE: src/.cloudgov/vars/pages-((deploy-env)).yml
          CF_PATH: src/admin-client
        on_failure:
          try:
            task: cancel-admin-client-deployment
            file: src/ci/partials/cancel-deployment.yml
            image: cf-image
            params:
              <<: *env-cf
              CF_APP_NAME: pages-admin-((deploy-env))

    on_failure:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: failure}
        - put: slack
          params:
            text: |
              :x: FAILED: admin client deployment on pages ((deploy-env))
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME?vars.deploy-env="((deploy-env))"|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

    on_success:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: success}
        - put: slack
          params:
            text: |
              :white_check_mark: SUCCESS: Successfully deployed admin client on pages ((deploy-env))
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME?vars.deploy-env="((deploy-env))"|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

  - name: deploy-queues-ui-pages
    plan:
      - get: src
        resource: pr-((deploy-env))
        params: {integration_tool: checkout}
        passed: [set-pipeline]
        trigger: true
      - put: gh-status
        inputs: [src]
        params: {state: pending}
      - get: cf-image
      - task: deploy-queues-ui
        file: src/ci/partials/deploy.yml
        image: cf-image
        params:
          <<: *env-cf
          CF_APP_NAME: pages-queues-ui-((deploy-env))
          CF_MANIFEST: src/.cloudgov/manifest.yml
          CF_VARS_FILE: src/.cloudgov/vars/pages-((deploy-env)).yml
          CF_PATH: src
        on_failure:
          try:
            task: cancel-queues-ui-deployment
            file: src/ci/partials/cancel-deployment.yml
            image: cf-image
            params:
              <<: *env-cf
              CF_APP_NAME: pages-queues-ui-((deploy-env))
    on_failure:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: failure}
        - put: slack
          params:
            text: |
              :x: FAILED: pages queues UI deployment on pages ((deploy-env))
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME?vars.deploy-env="((deploy-env))"|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))
    on_success:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: success}
        - put: slack
          params:
            text: |
              :white_check_mark: SUCCESS: Successfully deployed pages queues UI on pages ((deploy-env))
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME?vars.deploy-env="((deploy-env))"|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

  - name: nightly-tasks-pages
    plan:
      - get: src
        resource: pr-((deploy-env))
        params: {integration_tool: checkout}
        passed: [set-pipeline]
      - get: cf-image
      - get: nightly
        trigger: true
      - in_parallel:
        - task: restage-api
          file: src/ci/partials/restage.yml
          image: cf-image
          params:
            <<: *env-cf
            CF_APP_NAME: pages-((deploy-env))
        - task: restage-queues-ui
          file: src/ci/partials/restage.yml
          image: cf-image
          params:
            <<: *env-cf
            CF_APP_NAME: pages-queues-ui-((deploy-env))

  - name: e2e-test
    plan:
      - get: src
        resource: pr-((deploy-env))
        params: {integration_tool: checkout}
        trigger: true
        passed:
        - test-and-deploy-api-pages
        - test-and-deploy-admin-client-pages
        - deploy-queues-ui-pages
      - get: node
      - get: cf-image
      - put: gh-status
        inputs: [src]
        params: {state: pending}
      - task: get-app-env
        file: src/ci/partials/get-app-env.yml
        image: cf-image
        params:
          <<: *env-cf
          APP_ENV: ((deploy-env))
          CF_APP_NAME: pages-((deploy-env))
      - task: run-e2e-tests
        file: src/ci/partials/e2e-test.yml
        image: node
        params:
          APP_ENV: ((deploy-env))
          APP_HOSTNAME: https://((((deploy-env))-pages-domain))
          DOMAIN: ((((deploy-env))-pages-domain))
          PRODUCT: pages
        ensure:
          do:
          - task: remove-test-users
            file: src/ci/partials/remove-test-users.yml
            image: node
            params:
              APP_ENV: ((deploy-env))
              PRODUCT: pages
          - put: s3
    on_failure:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: failure}
        - put: slack
          params:
            text: |
              :x: FAILED: pages e2e testing on pages ((deploy-env))
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME?vars.deploy-env="((deploy-env))"|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))
    on_success:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: success}
        - put: slack
          params:
            text: |
              :white_check_mark: SUCCESS: Successfully passed e2e testing on pages ((deploy-env))
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME?vars.deploy-env="((deploy-env))"|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

  - name: audit-dependencies
    plan: 
      - get: src
        resource: pr-((deploy-env))
        params: {integration_tool: checkout}
        trigger: true
        passed: [set-pipeline]
      - get: node
      - in_parallel:
          - task: audit-app
            file: src/ci/partials/audit.yml
            image: node
            params:
              VULN_THRESHOLD: 8 # errors on critical or high
          - task: audit-admin
            file: src/ci/partials/audit-admin.yml
            image: node
            params:
              VULN_THRESHOLD: 8 # errors on critical or high
    on_failure:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: failure}
        - put: slack
          params:
            text: |
              :x: FAILED: dependency audit on pages ((deploy-env))
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME?vars.deploy-env="((deploy-env))"|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))
    on_success:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: success}
        - put: slack
          params:
            text: |
              :white_check_mark: SUCCESS: Successfully passed dependency audit on pages ((deploy-env))

  - name: nightly-site-bucket-key-rotator
    plan:
      - get: src
        resource: pr-((deploy-env))
        params: {integration_tool: checkout}
        passed: [set-pipeline]
      - get: nightly
        trigger: true
      - get: node
      - get: cf-image
      - task: install-deps-api
        file: src/ci/partials/install-deps-api.yml
        image: node
      - task: get-app-env
        file: src/ci/partials/get-app-env.yml
        image: cf-image
        params:
          <<: *env-cf
          APP_ENV: ((deploy-env))
          CF_APP_NAME: pages-((deploy-env))
      - task: rotate-keys
        file: src/ci/partials/rotate-bucket-keys.yml
        image: node
        params:
          <<: *env-cf
          APP_ENV: ((deploy-env))
          CF_APP_NAME: pages-((deploy-env))
        on_failure:
          put: slack
          params:
            text: |
              :x: FAILED: Rotate site bucket keys in ((deploy-env))
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME?vars.deploy-env="((deploy-env))"|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))
        on_success:
          put: slack
          params:
            text: |
              :arrows_counterclockwise: :key: SUCCESS: Rotate site bucket keys in ((deploy-env))
              <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME?vars.deploy-env="((deploy-env))"|View build details>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))
    
  - name: set-pipeline
    plan:
    - get: src
      resource: pr-((deploy-env))
      params: {integration_tool: checkout}
      trigger: true
    - set_pipeline: core
      file: src/ci/pipeline-dev.yml
      instance_vars:
        deploy-env: ((deploy-env))

############################
#  RESOURCES

resources:

  - name: pr-((deploy-env))
    type: pull-request
    check_every: 1m
    source:
      repository: ((pages-repository-path))
      access_token: ((gh-access-token))
      base_branch: main
      disable_forks: true
      ignore_drafts: false

  - name: nightly
    type: time
    source:
      start: 12:00 AM
      stop: 1:00 AM
      location: America/New_York

  - name: redis
    type: docker-image
    source:
      repository: redis
      tag: 5-alpine

  - name: postgres
    type: docker-image
    source:
      repository: postgres
      tag: 11-alpine

  - name: node
    type: docker-image
    source:
      repository: node
      tag: 20.9-bullseye

  - name: slack
    type: slack-notification
    source:
      url: ((slack-webhook-url))

  - name: gh-status
    type: cogito
    check_every: 1h
    source:
      owner: cloud-gov
      repo: pages-core
      access_token: ((gh-access-token))
      context_prefix: concourse

  - name: cf-image
    type: registry-image
    source:
      aws_access_key_id: ((ecr-aws-key))
      aws_secret_access_key: ((ecr-aws-secret))
      repository: harden-concourse-task
      aws_region: us-gov-west-1
      tag: ((harden-concourse-task-tag))

  - name: s3
    type: s3-resource
    source:
      access_key_id: ((test-results-access-key-id))
      secret_access_key: ((test-results-secret-access-key))
      bucket: ((test-results-bucket))
      region: us-gov-west-1
      change_dir_to: src
      options:
      - "--exclude '*'"
      - "--include 'playwright-report/*'"

############################
#  RESOURCE TYPES

resource_types:

  - name: cogito
    type: docker-image
    check_every: 24h
    source:
      repository: pix4d/cogito

  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

  - name: s3-resource
    type: docker-image
    source:
      repository: 18fgsa/s3-resource-simple